name: Android CI

on:
  push:
    branches: 
     - master
     - dev
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: mac:build

    steps:
    - uses: actions/checkout@v3
    - name : Write permission for Gradlew
    - run : chmode+x ./gradlew
    - name: set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '1.8'     
    - name: Build Android Application 
      run: ./gradlew buildDevRelease
